NVMESH-7379: fix gcc null warning, remove unused uuid_mgmt_format_to_urn_str
Fix a gcc warning that the function uuid_mgmt_format_to_urn_str() might
try to write to a null pointer. Seems odd, only would happen if the
caller passed null as an argument. But this function is no longer used
anywhere, so we can just delete it.

Fixes gcc 14.2.0 compiler warning in release mode with -O3 and
sanitizers:

    ../nvmeibt_common.c: In function ‘uuid_mgmt_format_to_urn_str’:
    ../nvmeibt_common.c:1112:24: error: null destination pointer [-Werror=format-overflow=]
     1112 |                 itr += sprintf(itr, "%02x", uuid[i] & 0xff);
          |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Change-Id: If91e596e8251d76e030304704f2e065190e1daea
Signed-off-by: Colin Bennett <cbennett@nvidia.com>