NVMESH-7379: fix maybe-uninitialized value gcc warning, old_data_ptr
With gcc optimizations turned on, it raises a warning about the function
persist_and_wire_buf_copy_data_to_section() which takes uses memcpy()
with old_data_ptr and sometimes uses its value, but sometimes it's
passed an old_data_ptr value that's uninitialized.

It's likely that the way this function is called, the branch that reads
old_data_ptr is only executed when it also happens to be initialized and
not null. But it's not obvious, and gcc can't be sure either.

To avoid such a warning, before calling the function, we always make
sure to initialize the old_data_ptr first.

Fixes gcc v14.2.0 -O3 warning:

    In function ‘persist_and_wire_buf_copy_data_to_section’,
        inlined from ‘realloc_and_upd_follower_persist_and_wire_bufs_with_incoming_data’ at ../nvmeibt_raft.c:713:3,
        inlined from ‘raft_follower_persist_due_to_incoming_msg_as_needed’ at ../nvmeibt_raft.c:2848:4:
    ../nvmeibt_raft.c:661:17: error: ‘old_data_ptr’ may be used uninitialized [-Werror=maybe-uninitialized]
      661 |                 memcpy(*dst_data_ptr, *old_data_ptr, old_len);  // might be that old_len==0
          |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ../nvmeibt_raft.c: In function ‘raft_follower_persist_due_to_incoming_msg_as_needed’:
    ../nvmeibt_raft.c:681:82: note: ‘old_data_ptr’ was declared here
      681 |         char                                                                    *old_data_ptr;
          |                                                                                  ^~~~~~~~~~~~

Change-Id: Id69e547162d5ca119b33bf886e3c7b1d12fc5aab
Signed-off-by: Colin Bennett <cbennett@nvidia.com>