NVMESH-7379: fix snprintf truncation warning for mgmt info message
Fix gcc error (as of gcc 14.2.0):

    ../nvmeibt_local_disk.c:923:64: error: ‘%s’ directive output may be truncated writing up to 99 bytes into a region of size 91 [-Werror=format-truncation=]

Change-Id: I265b6ef5078e8cdbcd4205db3713f0b8ea2cd2c0
Signed-off-by: Colin Bennett <cbennett@nvidia.com>