NVMESH-7379: fix gcc warning for zero-length filler struct field
Fix gcc release error where the optimizer warns about accessing beyond the end
of the zero-length internal struct array field. Since this field is not the
final field of the struct, it's not the usual "flexible array member" (only the
last field of a struct is a flexible array member).

- Add static assert statements to verify some field offsets, since the
  alignment hacks to get the struct layout right are pretty esoteric.

- Use a pointer to access the zero-length internal array when checking that it
  is all zeroed. By doing this, gcc stops warning (treated as error) about
  going beyond the end of the array.

Tested on gcc 14.2.0 the error was

    In file included from ../nvmeibt_ds_metadata.c:38:
    In function ‘__verify_persistent_md_unused_buf’,
        inlined from ‘nvmeibt_ds_metadata_validate_and_upgrade_persistent_metadata_as_needed’ at ../nvmeibt_ds_metadata.c:402:8:
    /home/cbennett/projects/nvmesh/toma/disk_seg_meta_data/nvmeibt_ds_md_old_versions_code.h:27:52: error: array subscript 3784 is outside the bounds of an interior zero-length array ‘const char[0]’ [-Werror=zero-length-bounds]
       27 |                 if (ctrl->__zeroed_filler_till_4K__[i] != 0) {
          |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
    In file included from ../nvmeibt_ds_metadata.c:1:
    ../nvmeibt_ds_metadata.h: In function ‘nvmeibt_ds_metadata_validate_and_upgrade_persistent_metadata_as_needed’:
    ../nvmeibt_ds_metadata.h:62:89: note: while referencing ‘__zeroed_filler_till_4K__’
       62 |         char                                                                            __zeroed_filler_till_4K__[0];   // must be 0 filled
          |                                                                                         ^~~~~~~~~~~~~~~~~~~~~~~~~
    In file included from ../utils/nvmeibt_utils.h:6,
                     from ../nvmeibt_common.h:23,
                     from ../nvmeibt_ds_metadata.h:4:
    In function ‘__verify_persistent_md_unused_buf’,
        inlined from ‘nvmeibt_ds_metadata_validate_and_upgrade_persistent_metadata_as_needed’ at ../nvmeibt_ds_metadata.c:402:8:
    /home/cbennett/projects/nvmesh/toma/disk_seg_meta_data/nvmeibt_ds_md_old_versions_code.h:28:146: error: array subscript 3784 is outside the bounds of an interior zero-length array ‘const char[0]’ [-Werror=zero-length-bounds]
       28 |                         N_Ef(t_11_upgrade_persistent_md, "metadata->__zeroed_filler_till_4K__[@IND]=@RV != 0", i, ctrl->__zeroed_filler_till_4K__[i]);
          |                                                                                                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
    /home/cbennett/projects/nvmesh/toma/nvmeibt_debug.h:163:103: note: in definition of macro ‘NVMEIBT_THROTTLED_SYSLOG’
      163 |         #define NVMEIBT_THROTTLED_SYSLOG(SYSLOG_LOG_LVL, __FMT, ...) syslog(SYSLOG_LOG_LVL, __FMT, ## __VA_ARGS__)
    --
          |         ^~~~~~~~~~~~~~
    /home/cbennett/projects/nvmesh/toma/nvmeibt_debug.h:198:31: note: in expansion of macro ‘_NMIRROR_LOGLEVEL’
      198 | #define N_Ef(name, fmt, ...)  _NMIRROR_LOGLEVEL(Ef, LOG_ERR, name, NVMEIB_LOG_ETERNAL, TOMA_ERR_STR, fmt, ## __VA_ARGS__)
          |                               ^~~~~~~~~~~~~~~~~
    /home/cbennett/projects/nvmesh/toma/disk_seg_meta_data/nvmeibt_ds_md_old_versions_code.h:28:25: note: in expansion of macro ‘N_Ef’
       28 |                         N_Ef(t_11_upgrade_persistent_md, "metadata->__zeroed_filler_till_4K__[@IND]=@RV != 0", i, ctrl->__zeroed_filler_till_4K__[i]);
          |                         ^~~~
    ../nvmeibt_ds_metadata.h: In function ‘nvmeibt_ds_metadata_validate_and_upgrade_persistent_metadata_as_needed’:
    ../nvmeibt_ds_metadata.h:62:89: note: while referencing ‘__zeroed_filler_till_4K__’
       62 |         char                                                                            __zeroed_filler_till_4K__[0];   // must be 0 filled
          |                                                                                         ^~~~~~~~~~~~~~~~~~~~~~~~~

Change-Id: I379228b7f75d103631e8b1950c4a166022f6f589
Signed-off-by: Colin Bennett <cbennett@nvidia.com>