NVMESH-7379: fix null pointer dereference
In this log statement, the struct pointer was already found to be null, but
then a field was accessed through it, meaning that there will be an invalid
memory access (segfault etc.) if this code is actually executed.

Since we don't have any data, we just have to omit the UUID from the log
statement and make the best of it.

Tested with gcc 14.2.0, the error was:

    In function ‘trace_nvmeibt_ETER_bs8923l’,
        inlined from ‘nvmeibt_seg_active_fill_metadata_ctrl_header’ at ../nvmeibt_ds_metadata.c:260:3,
        inlined from ‘nvmeibt_seg_active_fill_metadata_ctrl_header’ at ../nvmeibt_ds_metadata.c:254:5:
    /home/cbennett/projects/nvmesh/toma/unitest/99bin/release/nvmeibt_ds_metadata.c_gen_events.h:978:97: error: array subscript 0 is outside array bounds of ‘union nvmeib_uuid[
    0]’ [-Werror=array-bounds=]
      978 |                                 (uuid_le_1?(*((struct __binary_tracer_const_buf_16*) uuid_le_1)):((struct __binary_tracer_const_buf_16) {{0}}))
          |                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In function ‘nvmeibt_seg_active_fill_metadata_ctrl_header’:
    cc1: note: source object is likely at address zero

Change-Id: I4d127d5d13cd1437be3668dd2294550fd6cf3281
Signed-off-by: Colin Bennett <cbennett@nvidia.com>