NVMESH-7379: suppress spurious sprintf() destination warning
For some reason gcc is confused and warning that the destination might
be null. This happens even if we check that the caller passed a non-null
pointer to us. Seems related to the pointer arithmetic which confuses
gcc's warning checks.

Just suppress the warning with compiler pragma because other fixes were
not successful.

This hexdump() function is not referenced anywhere, but per the commit
message that added it, maybe it will be used again for debugging.
Otherwise we might just delete it.

Fix spurious gcc 14.2.0 warning when address sanitizers are enabled on
this sprintf() call:

    ../nvmeibt_disk_metadata.c:74:22: error: null destination pointer [-Werror=format-overflow=]

Change-Id: Ib7037559f6161fd864acf72d01913d3c8283dabc
Signed-off-by: Colin Bennett <cbennett@nvidia.com>