NVMESH-7379: fix gcc null format string warning in nvmeibt_Str_sprintf
When gcc is compiling with sanitizers and optimizations as well as the
strict warnings, it raises warning for vsnprintf() when we just pass
the 'format' value on to it without checking that the caller provided a
non-null pointer.

Add a check for this to make gcc happy.

Fixes this warning (as of gcc 14.2.0):

    ../utils/nvmeibt_str.c:70:31: error: null format string [-Werror=format-truncation=]

Change-Id: I6386c49b6b42d54db76b2e5dafa08daa4a827866
Signed-off-by: Colin Bennett <cbennett@nvidia.com>