TomaSimu: fix intermittent trace AttributeError incremental build failure
Avoid occasional failures of incremental (non-clean) builds caused by
some .trace.json file issues that crash the gen_probes2.py script.

The solution here is to separate the generation and the merging steps so
that separate intermediate files are used for each kind of step.

The incremental build done with `make -j` seemed to have either a race
condition or some incremental build problem, since occasionally it
produes a list vs dict mismatch in the JSON from what the Python script
expects:

	Autogen code  Done
	Generating trace JSON 99bin/debug/obj/./toma_in_sandbox.trace.json
	Generating trace JSON /home/cbennett/projects/nvmesh/toma/unitest/99bin/debug/obj/toma_in_sandbox.trace.json
	Generating gen_events header 99bin/debug/obj/./mgmt_sim.c_gen_events.h
	Generating gen_events header /home/cbennett/projects/nvmesh/toma/unitest/99bin/debug/obj/mgmt_sim.c_gen_events.h
	Traceback (most recent call last):
	  File "/home/cbennett/projects/nvmesh/tools/pre_processor/gen_probes2.py", line 657, in <module>
	    sys.exit(main())
		     ~~~~^^
	  File "/home/cbennett/projects/nvmesh/tools/pre_processor/gen_probes2.py", line 639, in main
	    d = Dictionary(args.compiled_dict_path)
	  File "/home/cbennett/projects/nvmesh/tools/pre_processor/gen_probes2.py", line 102, in __init__
	    d = dictionary_tools.read_dictionary_and_verify(path)
	  File "/home/cbennett/projects/nvmesh/tools/pre_processor/dictionary_tools.py", line 180, in read_dictionary_and_verify
	    verify_dictionary(d.get("dictionary"))
			      ^^^^^
	AttributeError: 'list' object has no attribute 'get'
	make: *** [Makefile:258: 99bin/debug/obj/./mgmt_sim.c_gen_events.h] Error 1
	make: *** Waiting for unfinished jobs....
	Traceback (most recent call last):
	  File "/home/cbennett/projects/nvmesh/tools/pre_processor/gen_probes2.py", line 657, in <module>
	    sys.exit(main())
		     ~~~~^^
	  File "/home/cbennett/projects/nvmesh/tools/pre_processor/gen_probes2.py", line 639, in main
	    d = Dictionary(args.compiled_dict_path)
	  File "/home/cbennett/projects/nvmesh/tools/pre_processor/gen_probes2.py", line 102, in __init__
	    d = dictionary_tools.read_dictionary_and_verify(path)
	  File "/home/cbennett/projects/nvmesh/tools/pre_processor/dictionary_tools.py", line 180, in read_dictionary_and_verify
	    verify_dictionary(d.get("dictionary"))
			      ^^^^^
	AttributeError: 'list' object has no attribute 'get'
	make: *** [Makefile:258: /home/cbennett/projects/nvmesh/toma/unitest/99bin/debug/obj/mgmt_sim.c_gen_events.h] Error 1
	mv: cannot create regular file '99bin/debug/obj/./toma_in_sandbox.trace.json': File exists
	cp: cannot create regular file '/home/cbennett/projects/nvmesh/toma/unitest/99bin/debug/obj/dict.4227445738.json': File exists

Change-Id: I913f3d57c7c2ccc7f13310fdabeb879e8b854932
Signed-off-by: Colin Bennett <cbennett@nvidia.com>