NVMESH-7379: fix CSV long lines buffer overrun in release mode
When this CSV parsing function encounters a long line (>=512 bytes), it
is checked by a call to NTOMA_ASSERT(), but this macro sometimes does
return control to the caller (in release mode, instead of aborting the
program), so that would allow a buffer overrun later when using it.

By explicitly checking that the line fits in the buffer and skipping
this loop iteration if so, we avoid the possibility of undefined
behavior.

Fixes gcc v14.2.0 warning:

    ../nvmeibt_read_config.c: In function ‘nvmeibt_parse_buf’:
    ../nvmeibt_read_config.c:779:32: error: writing 1 byte into a region of size 0 [-Werror=stringop-overflow=]
      779 |                 line[line_len] = '\0';
          |                 ~~~~~~~~~~~~~~~^~~~~~
    ../nvmeibt_read_config.c:695:49: note: at offset 512 into destination object ‘line’ of size 512
      695 |         char                                    line[NVMEIBT_MAX_CSV_LINE_LENGTH];
          |                                                 ^~~~
    ../nvmeibt_read_config.c:779:32: error: writing 1 byte into a region of size 0 [-Werror=stringop-overflow=]
      779 |                 line[line_len] = '\0';
          |                 ~~~~~~~~~~~~~~~^~~~~~
    ../nvmeibt_read_config.c:695:49: note: at offset 512 into destination object ‘line’ of size 512
      695 |         char                                    line[NVMEIBT_MAX_CSV_LINE_LENGTH];

Change-Id: Icf835350f8df96ebe77fb0aa0c4c35f828c0142f
Signed-off-by: Colin Bennett <cbennett@nvidia.com>