NVMESH-7379: fix spurious gcc warning uninit new_guaranteed_sw_ver
To avoid a spurious gcc warning when in release mode with sanitizers
enabled, initialize new_guaranteed_sw_ver to zero.

In reality, the code that reads this variable is only triggered if it
was initialized in the hashtable iteration, but gcc doesn't know this.

Fixes the gcc 14.2.0 warning:

    In function ‘trace_nvmeibt_LONG_k09j227’,
        inlined from ‘set_guaranteed_sw_ver’ at ../nvmeibt_raft.c:2351:4,
        inlined from ‘raft_leader_send_appendentries_to_all_peers.isra’ at ../nvmeibt_raft.c:2506:3:
    /home/cbennett/projects/nvmesh/toma/unitest/99bin/release/nvmeibt_raft.c_gen_events.h:8359:67: error: ‘new_guaranteed_sw_ver’ may be used uninitialized [-Werror=maybe-uninitialized]
     8359 |                         *(struct __tracedata_k09j227__struct*)ptr = (struct __tracedata_k09j227__struct) {
          |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     8360 |                                 id_k09j227,
          |                                 ~~~~~~~~~~~
     8361 |                                 tid_int_nofmt_0,
          |                                 ~~~~~~~~~~~~~~~~
     8362 |                                 software_version_1,
          |                                 ~~~~~~~~~~~~~~~~~~~
     8363 |                                 software_version_2,
          |                                 ~~~~~~~~~~~~~~~~~~~
     8364 |                                 int_3,
          |                                 ~~~~~~
     8365 |                                 int_4
          |                                 ~~~~~
     8366 |                         };
          |                         ~
    ../nvmeibt_raft.c: In function ‘raft_leader_send_appendentries_to_all_peers.isra’:
    ../nvmeibt_raft.c:2330:57: note: ‘new_guaranteed_sw_ver’ was declared here
     2330 |         uint32_t                                        new_guaranteed_sw_ver;
          |                                                         ^~~~~~~~~~~~~~~~~~~~~

Change-Id: I34ac44132dbe96e4eaaf82e5abaff15508c5a931
Signed-off-by: Colin Bennett <cbennett@nvidia.com>