NVMESH-7379: use nvmeib_strlcpy() instead of strncpy() and manual termination
Avoid spurious gcc warning when optimizations and address/undefined
sanitizer is enabled, from use of strncpy(). It's spurious since we
actually did always terminate the string on the next line, but it's
cleaner to use the strlcpy() function which is the safe replacement for
strncpy().

Both -fsanitize=address and -fsanitize=undefined trigger the
-Wstringop-truncation warning. When GCC enables the Address Sanitizer or
UndefinedBehavior Sanitizer, it performs more aggressive static analysis
of buffer operations.

Fixes gcc 14.2.0 warning:

    toma/nvmeibt_node.c:65:9: error: ‘strncpy’ output may be truncated
    copying 64 bytes from a string of length 255
    [-Werror=stringop-truncation]

Change-Id: Ifcb1fd42dcc1bad09d2029d73d80b7c182890dc8
Signed-off-by: Colin Bennett <cbennett@nvidia.com>