NVMESH-7379: fix kafka group name length warning for snprintf buffer
Fix this gcc warning when compiling in release mode, where the snprintf() call
might truncate the number when formatting into the buffer. This is not a
soundness issue since snprintf() will always terminate the string. We just
enlarge the buffer slightly so that it can accommodate all possible values.

Fixes this error (reported here on gcc v14.2.0):

	../nvmeibt_kafka.c:1496:62: error: ‘%ld’ directive output may be truncated writing between 1 and 19 bytes into a region of size 17 [-Werror=format-truncation=]
	../nvmeibt_kafka.c:1665:62: error: ‘%ld’ directive output may be truncated writing between 1 and 19 bytes into a region of size 17 [-Werror=format-truncation=]

Change-Id: Ie5629537e978e413c77b25ec20aaa6f596cbaa8d
Signed-off-by: Colin Bennett <cbennett@nvidia.com>